version: '3.5'
services:
  webui:
    image: nginx:latest
    container_name: webui
    networks:
      - internal
    volumes:
      - /docker/nginx:/etc/nginx
      - /docker/certs:/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - groundhog
    restart: unless-stopped
  groundhog:
    image: marsara9/groundhog:latest
    container_name: groundhog
    networks:
      - internal
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=America/New_York
    #ports:
    #  - 8080:8080
    volumes:
      - /var/run/dbus:/var/run/dbus
      # - /docker/groundhog/database:/router/database
    restart: unless-stopped
networks:
  internal:
    name: internal
    driver: bridge
