version: '3.5'
services:
  # webui:
  #   image: nginx:latest
  #   container_name: webui
  #   networks:
  #     - internal
  #   volumes:
  #     - /docker/nginx:/etc/nginx
  #     - /docker/certs:/certs
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - server
  #   restart: unless-stopped
  router:
    image: marsara9/vpnrouter:latest
    container_name: vpnrouter
    networks:
      - internal
    cap_add:
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
    #   - PUID=1000
    #   - PGID=1000
      - TZ=America/New_York
    ports:
      - 8080:8080
    volumes:
      - /var/run/dbus:/var/run/dbus
    restart: unless-stopped
networks:
  internal:
    name: internal
    driver: bridge
