name: Docker Build Multiplatform
run-name: ${{ github.actor }} is building and pushing to docker-hub.
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: marsara9/groundhog:latest
          allow: |
            security.insecure